- name: Installation certbot
  hosts: clientservers
  become: true
  gather_facts: yes

  tasks: 
  - name: install snapd service
    shell: apt-get install snapd -y 
  - name: Install core
    shell: snap install core

  - name: refresh core
    shell: snap refresh core

  - name: install certbot
    shell: snap install --classic certbot

  - name: create sym link
    file:
      src: /snap/bin/certbot
      dest: /usr/bin/certbot
      owner: root
      group: root
      state: link


  - name: generate certifcate
    shell: certbot certonly --standalone --non-interactive --agree-tos -m foo@bar.org -d "$(hostname).domain.tld"
